---
- name: Install nginx
  yum: name=nginx state=present

- name: Copy nginx configuration for wordpress
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: insert firewalld rule for nginx (HTTP)
  firewalld: port={{ nginx_http_port }}/tcp permanent=true state=enabled immediate=yes

- name: insert firewalld rule for nginx (HTTPS)
  firewalld: port={{ nginx_https_port }}/tcp permanent=true state=enabled immediate=yes

- name: http service state
  systemd: name=nginx.service state=started enabled=yes
