---
- name: Copy the NGINX repository definition
  copy: src=nginx.repo dest=/etc/yum.repos.d/

- name: Create the GPG key for NGINX
  copy: src=RPM-GPG-KEY-NGINX dest=/etc/pki/rpm-gpg

- name: set up the Confluence hostnames
  lineinfile:
    dest: /etc/hosts
    state: present
    line: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} {{ server_hostname }} {{ server_hostname }}.{{ server_domainname }}"
